version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - ${EX_PORT}:${PORT}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - ${NETWORK_NAME}
networks:
  arcadia:
    